import json
import os
import glob
from pathlib import Path
import re

def migrate_inventory():
    # Paths
    maintaindb_dc = Path('maintaindb/_dc')
    private_inventory_path = Path('private_inventory.json')
    failed_path = Path('private_inventory_failed.json')
    refactor_doc_path = Path('REFACTORING_PLAN.md')

    # 1. Build mapping from code to product_id
    code_to_id = {}
    print("Building code-to-id mapping...")
    
    # Load catalog.json for mapping
    catalog_path = Path('assets/data/catalog.json')
    if catalog_path.exists():
        with open(catalog_path, 'r', encoding='utf-8') as f:
            cat_data = json.load(f)
            adventures = cat_data.get('adventures', [])
            for adv in adventures:
                code = adv.get('c')
                product_id = adv.get('i')
                if code and product_id:
                    code_to_id[code.strip().upper()] = str(product_id)

    # Also load from individual files to be sure
    for json_file in maintaindb_dc.glob('*.json'):
        try:
            with open(json_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
                code = data.get('code')
                product_id = data.get('product_id')
                if code and product_id:
                    code_to_id[code.strip().upper()] = str(product_id)
        except Exception as e:
            print(f"Error reading {json_file}: {e}")

    # Manual overrides for common mismatches
    overrides = {
        "DDAL-EB-01": "296403",
        "DDAL-EB-02": "299680",
        "DDAL-EB-03": "302373",
        "DDAL-EB-04": "305024",
        "DDAL-EB-05": "308553",
        "DDAL-EB-06": "310332",
        "DDAL-EB-07": "312336",
    }

    # 2. Load private inventory
    # Start with original codes from issue attachment (hardcoded here for safety)
    original_inventory = {
      "CCC-3MAGS-01": "https://drive.google.com/open?id=1pIq8-8VvYWv5gSqPccb3wMUTrm3vJ73k",
      "CCC-AETHER01-01": "https://drive.google.com/open?id=1pbkfyphrWcQqPpGl_ecKMvajbrvPRcyC",
      "CCC-AETHER01-02": "https://drive.google.com/open?id=1SW98WxxFAq4qt_rVszOQe4zCvwHF_gep",
      "CCC-ALMOG-01": "https://drive.google.com/open?id=1tsCE91w9uOLfM4Bao0y6QMs2Fmh8_ie5",
      "CCC-ALMOG-03": "https://drive.google.com/open?id=15mF8uyB5ucnuoL_jBH--Z5ZI4DBbpekj",
      "CCC-AMER-01": "https://drive.google.com/open?id=1wdjpiniKx7fEZmD9D4Ysjp7uFdmFcZ5N",
      "CCC-AN-01": "https://drive.google.com/open?id=1HCuFW6G1uheUIqtpXj6_pOcT9bRocgu2",
      "CCC-AN-02": "https://drive.google.com/open?id=1yGZ8f5POVXfaYGtb_vpyFLoAZ6FYuloj",
      "CCC-AN-03": "https://drive.google.com/open?id=1WxnV7WT5_7SZWQrsYEqWBo3C1HaGKTwN",
      "CCC-ANIME-1-1": "https://drive.google.com/open?id=1j6FM4FwhMXbHe5Uenhuqc3lhAKM0p43e",
      "CCC-ANIME-1-2": "https://drive.google.com/open?id=1Qon-K8kl_bg3r-8nR5GL_TD8JhvSj9WA",
      "CCC-ANIME-1-3": "https://drive.google.com/open?id=17k2TlM1hCgB3gh3gP_6lMW-FZhY4SkUA",
      "CCC-APL-01-01": "https://drive.google.com/open?id=1NctB20jMEPWkIEk1-oYUk6zMYQ_DE3QZ",
      "CCC-BLD 1-0": "https://drive.google.com/open?id=1R7kPEldaCxoqCi25MM2O8TBZn9f0K6wF",
      "CCC-BLD-0103": "https://drive.google.com/open?id=15rec2YH_McWdA75TuJvYG491A8yij3QD",
      "CCC-BLD-11": "https://drive.google.com/open?id=0B9NR7rHEJNUGekV4Q0hQMFRUeW8",
      "CCC-BLD-12": "https://drive.google.com/open?id=0B9NR7rHEJNUGZUM3UmNQdEE3Nnc",
      "CCC-BMG MOON 1-1": "https://drive.google.com/open?id=1tW-iPwxLXNTuX43RNhLq6nUtbkgW6KYm",
      "CCC-BMG-01": "https://drive.google.com/open?id=0B9NR7rHEJNUGOThmNGVoemx1cHc",
      "CCC-BMG-02": "https://drive.google.com/open?id=0B9NR7rHEJNUGOFhlc2Q3eENLSXc",
      "CCC-BMG-03": "https://drive.google.com/open?id=0B9NR7rHEJNUGSnB6cUJINUk2T28",
      "CCC-BMG-04": "https://drive.google.com/open?id=0B9NR7rHEJNUGbURXRHItdE5ZZlU",
      "CCC-BMG-05": "https://drive.google.com/open?id=0B9NR7rHEJNUGcVRoWWVHcklaQXc",
      "CCC-BMG-06": "https://drive.google.com/open?id=0B9NR7rHEJNUGemZocENaRHpFMFk",
      "CCC-BMG-07": "https://drive.google.com/open?id=0B9NR7rHEJNUGUTl3TW8yTTJEcjQ",
      "CCC-BMG-08": "https://drive.google.com/open?id=0B9NR7rHEJNUGSTYxQi1FY3JQbU0",
      "CCC-BMG-09": "https://drive.google.com/open?id=0B9NR7rHEJNUGV3FSYWgtT0NQMVk",
      "CCC-BMG-10": "https://drive.google.com/open?id=0B9NR7rHEJNUGOXpXN256Rl81bDg",
      "CCC-BMG-11": "https://drive.google.com/open?id=0B9NR7rHEJNUGTnZVUjFvM29SRTg",
      "CCC-BMG-12": "https://drive.google.com/open?id=0B9NR7rHEJNUGeG1DWTBuQk91XzA",
      "CCC-BMG-13": "https://drive.google.com/open?id=0B9NR7rHEJNUGTmY3Q3JIbGl1UW8",
      "CCC-BMG-14": "https://drive.google.com/open?id=0B9NR7rHEJNUGSldwbjZCd1R1UUk",
      "CCC-BMG-15": "https://drive.google.com/open?id=0B9NR7rHEJNUGQUticElKSUJEVVE",
      "CCC-BMG-16": "https://drive.google.com/open?id=0B9NR7rHEJNUGQVBiSVdmNmtKaWc",
      "CCC-BMG-17": "https://drive.google.com/open?id=0B9NR7rHEJNUGcVg0WTB4R3JDY28",
      "CCC-BMG-18": "https://drive.google.com/open?id=0B9NR7rHEJNUGTHpwSm9FcGdPdEk",
      "CCC-BMG-19": "https://drive.google.com/open?id=0B9NR7rHEJNUGRFViT0ptazYzSE0",
      "CCC-BMG-20": "https://drive.google.com/open?id=0B9NR7rHEJNUGdk1Yd0R4Q3p4TFE",
      "CCC-BMG-21": "https://drive.google.com/open?id=0B9NR7rHEJNUGYTdWOUVWa09XTnM",
      "CCC-BMG-22": "https://drive.google.com/open?id=1sOT5HtQluGY2vNHeTrUmJKvvoaSIpohY",
      "CCC-BMG-23": "https://drive.google.com/open?id=1qZBaGcr0XiqVVurHw_EE2BP7iTt9folE",
      "CCC-BMG-24": "https://drive.google.com/open?id=1YlwB-fepkGQeVuYag70CO9RbPSTltgII",
      "CCC-BMG-25": "https://drive.google.com/open?id=11-8htRH9ARSHpRYD_ocM5qXLVu-PmyBl",
      "CCC-BMG-26": "https://drive.google.com/open?id=1iEsN-qqVgXFtG9OW4tZsBeWLntIsuSUj",
      "CCC-BMG-27": "https://drive.google.com/open?id=1ul3sf_zscwJIpMdEf5gd3i62z1ce0apn",
      "CCC-BMG-28": "https://drive.google.com/open?id=1xn0nirySF4ucR_HcYtTVv8AAqm13Rk1B",
      "CCC-BMG-29": "https://drive.google.com/open?id=1NbUu2_ER9TQ1Yf5-wa0umv83Lok_9sif",
      "CCC-BMG-30": "https://drive.google.com/open?id=1xzbIxe4_vGRQEbXmBqp8UKF6TK2alMF8",
      "CCC-BMG-31": "https://drive.google.com/open?id=1GF-VJZNzTztwNJeh3K-uDMeyGzbOepy7",
      "CCC-BMG-32": "https://drive.google.com/open?id=1hoIHbplwMXSFo47mauBThwwmjt5WxPWg",
      "CCC-BMG-33": "https://drive.google.com/open?id=1CGLDa5v6GlOOcXp0xxESaSN6L_5Woafr",
      "CCC-BMG-34": "https://drive.google.com/open?id=1QYrZ66vkXpxlFQ2uqEPiI4k7GysbXeBT",
      "CCC-BMG-35": "https://drive.google.com/open?id=193Sb7LTNxfd4zfmv2TOaMr6dKPdy1bDg",
      "CCC-BMG-36": "https://drive.google.com/open?id=123YpNcsC_X8kSKnEn9Fa8N1KVbDwZdPA",
      "CCC-BMG-37": "https://drive.google.com/open?id=1baJ6M7z2c6MMBmsoNG4G-HxLwYBAjVIZ",
      "CCC-BMG-38": "https://drive.google.com/open?id=1K32fitnKW7twUrbmKqOf_JFfXsUJKPQe",
      "CCC-BMG-39": "https://drive.google.com/open?id=1cXyU7Q77lsrO7-XQmQeoSZ8M9NgJLty0",
      "CCC-BMG-40": "https://drive.google.com/open?id=1_7GarulrSFnwftBPGHB6gCuan2qJq2Cn",
      "CCC-BMG-41": "https://drive.google.com/open?id=1wEwx2WwcA5_we107BeaO2u4IFR4hDEUX",
      "CCC-BMG-42": "https://drive.google.com/open?id=10yZyl6kRcmDLYs-Zkg9iGn7VOVUBECKU",
      "CCC-BMG-43": "https://drive.google.com/open?id=1HJ8HGeTGnti7wCHINkZCuD-g4ryV3Nie",
      "CCC-BMG-44": "https://drive.google.com/open?id=1wDcIW4T2pHG1QqI0mUFFTKzJmP5U_Lyv",
      "CCC-BMG-45": "https://drive.google.com/open?id=1Qwz3IaIVUZe9qHzporZzGVzpuEv6lulY",
      "CCC-BMG-46": "https://drive.google.com/open?id=1Fy6Nr8DJ5Tzkcs3B8obTJvAOqto52Q3A",
      "CCC-BMG-47": "https://drive.google.com/open?id=1r3orFtDox5LPp_mEPU6QaQAMCaoyf_ha",
      "CCC-BMG-48": "https://drive.google.com/open?id=1nuZEP4OLUTQa3c57FmFpSvtUUiTWJfaH",
      "CCC-BMG-HILL1S": "https://drive.google.com/open?id=0B9NR7rHEJNUGUmowcVFHX05XMTA",
      "CCC-BMG-HILL2S": "https://drive.google.com/open?id=1z3YsRIwkYNLMQsWd9_cdJggcfonjVqLr",
      "CCC-BMG-MOON": "https://drive.google.com/open?id=1_MIiYUZxBr6ZdskH3b6-gF-C9S0N9crn",
      "CCC-BMG-MOON2-1": "https://drive.google.com/open?id=1kB9zmGOPpbUSaqBeR2Uam6Z1_8s5b3SP",
      "CCC-BMG-MOON2-2": "https://drive.google.com/open?id=1ESAcBKV1BA6DBIhhGr-HB_3f7UvalStK",
      "CCC-BMG-MOON2-3": "https://drive.google.com/open?id=1ts_eFPtCOgt3ht1iUynZ0VzvTnXF8rAd",
      "CCC-BWM-001": "https://drive.google.com/open?id=1dFX1IBTYde_bSQTjO9WqW_wIAEpIu6aJ",
      "CCC-BWM-002": "https://drive.google.com/open?id=1Fx5NNG8v-KWmHpC3VNtUhgF4pGDTlTZs",
      "CCC-BWM-003": "https://drive.google.com/open?id=1LdSRGIZYP--DDyJAx9NG3fiwXrrNllNd",
      "CCC-BWM-06": "https://drive.google.com/open?id=1KKfNLGATQO-CJtgjbRdxyT-0y0vr3soX&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-CIC-01": "https://drive.google.com/open?id=0B9NR7rHEJNUGZzdaU1ZvOTVvb28",
      "CCC-CIC-02": "https://drive.google.com/open?id=0B9NR7rHEJNUGNmFSSFBqRFN4S28",
      "CCC-CIC-03": "https://drive.google.com/open?id=0B9NR7rHEJNUGLWR4MjJmeTBOV3c",
      "CCC-CIC-04": "https://drive.google.com/open?id=0B9NR7rHEJNUGbUsxSzNEbTJWUlE",
      "CCC-CIC-05": "https://drive.google.com/open?id=1x-of01SwPAhwMpbFiZsw9Bs9Fzld5CKK",
      "CCC-CIC-06": "https://drive.google.com/open?id=153N6IiRfQmdRFDbXFB1n7EwVm0dm6I2v",
      "CCC-CIC-07": "https://drive.google.com/open?id=1tjj8uVei3uyHwasvSpv1iczz0DYL4KwV",
      "CCC-CIC-08": "https://drive.google.com/open?id=1ao8IDyqiyPR2L7eeeGSP_zvpmP3r_LTZ",
      "CCC-CIC-09": "https://drive.google.com/open?id=1_sr-B-EVm7prNxrTgoOSkuoMHJmxb0NW",
      "CCC-CIC-10": "https://drive.google.com/open?id=1flNpVWU7SVuwk8DDjLiyQ-vRrJJSGClh",
      "CCC-CIC-11": "https://drive.google.com/open?id=1A8DJrHmqn2jHXWgDgOZ1atDRfJaXjVr1",
      "CCC-CIC-12": "https://drive.google.com/open?id=1B2n7-33Ch8OZ7MDbL-6H_UXpou0sUYzx",
      "CCC-DDSC-01": "https://drive.google.com/open?id=0B9NR7rHEJNUGdndwYXJHbEJOWXc",
      "CCC-DDSC-02": "https://drive.google.com/open?id=0B9NR7rHEJNUGMnVab0V5ZElPSHc",
      "CCC-DES01-01": "https://drive.google.com/open?id=1DeKm6F8LgmHkVMaZul7cWeSa9iqmsc31",
      "CCC-DES01-02": "https://drive.google.com/open?id=1RCiFVY8qqJUytxlUsjeahiM4js8qtdHW",
      "CCC-DES01-04": "https://drive.google.com/open?id=1TvCsgb-AjYO0vSX4KIlpjGaKrkZArM4A",
      "CCC-DRUID-01": "https://drive.google.com/open?id=1gPz4M57-CFiC4TFwWCi-5VRE0M4WfsI4",
      "CCC-ELF-01": "https://drive.google.com/open?id=1fE4NZF6USon1rENkBmyxmWregEUvOMKK",
      "CCC-ELF-02": "https://drive.google.com/open?id=1jlgr_nA9bj_IhqjMKoYpM8dZN8HCJgXG",
      "CCC-ELO-01": "https://drive.google.com/open?id=1TmiqA598BKoJ-t3FrohDRqMRBeWZ6ArF",
      "CCC-ELO-02": "https://drive.google.com/open?id=1nPUWhAnY2QLlUkJlwQLMvVzIJN9VZaZs",
      "CCC-FC3-01-02": "https://drive.google.com/open?id=1R0ChmylDO966Jm0ZllpYnTXzu9OhH3SP",
      "CCC-FC3-01-03": "https://drive.google.com/open?id=1X7RFUioqceLSHrEnU2yNbtUgbCfnJGSU",
      "CCC-FXC-01": "https://drive.google.com/open?id=1OIeaoNE0K4TTYvByEtcZ7pevPQMGPZpx&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-GAD01-01": "https://drive.google.com/open?id=1KsieG8kTXzH1tCHR7r6IOisJlRU7T5BA",
      "CCC-GAD01-02": "https://drive.google.com/open?id=1Etgq2riH6wiHXGB1wSW2kzAwd4_3KJbR",
      "CCC-GAD01-03": "https://drive.google.com/open?id=1sp2IdgB6qiPiHyVkxvRZCOpxfTyfgZa-",
      "CCC-GARY-01": "https://drive.google.com/open?id=0B9NR7rHEJNUGdTBXLXh4VVJFemc",
      "CCC-GARY-02": "https://drive.google.com/open?id=0B9NR7rHEJNUGRV91eWVMTjd2TEU",
      "CCC-GARY-03": "https://drive.google.com/open?id=0B9NR7rHEJNUGYXpYWDA5cHVRbUk",
      "CCC-GARY-04": "https://drive.google.com/open?id=1ed1AWRI7XCloKrP-zjlZetC1Bn1S7vsF&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-GARY-05": "https://drive.google.com/open?id=1eYJcU8C9vu3qCUjsv6b73tJ_oJBaKQVj&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-GARY-06": "https://drive.google.com/open?id=1eV0SRLBh3hkvDOPhYyJww2KLxAZWLfVU&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-GARY-07": "https://drive.google.com/open?id=1eT8LqvgXFvBG16P3L2Yog5hSGiGebWuM&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-GARY-08": "https://drive.google.com/open?id=1eIsEgU2GiN0xm2MIvx8unT1FtfQpUioo&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-GARY-09": "https://drive.google.com/open?id=1ezznnsBKXGaFDB94SuProdo21VRyzOsS&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-GEL-01": "https://drive.google.com/open?id=1LHx0D3zFVnhuPCDqtjOhYV4klepozEE2&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-GHC-01": "https://drive.google.com/open?id=1ez914ND0SV-Za2ATeGGsETAR62M0Rx8D&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-GHC-02": "https://drive.google.com/open?id=1ewqRsuMXttFOvuZuAfsTisUNl9hrHlPz&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-GHC-03": "https://drive.google.com/open?id=1fDMeNj58joWrOYdW0mpqeygKurNaENM9&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-GHC-04": "https://drive.google.com/open?id=1j96OHEUaCQ0fACKyI6ebWQ9MJIs_ElQk",
      "CCC-GHC-05": "https://drive.google.com/open?id=125xQXtLQQB4Amu-UYtPk27fKM-caTGcx",
      "CCC-GHC-06": "https://drive.google.com/open?id=1Bw-WA2RBbL314UKCJ7iutY0-V1ljuX5e",
      "CCC-GHC-07": "https://drive.google.com/open?id=1dM80zcWc0mVqoTD-T0jCPgSOEkyDdsQ2",
      "CCC-GHC-08": "https://drive.google.com/open?id=1fpTcWo-PApIgx2eLgnYr27iWybCy0zvD",
      "CCC-GHC-09": "https://drive.google.com/open?id=1eibx_b79QpsdJ1yEn86l_wUpkbLOopBF",
      "CCC-GHC-BORDER": "https://drive.google.com/open?id=1XF236YKA0pHBqXpyKu1qnn6fDAhK_4xd",
      "CCC-GHCBK1-01": "https://drive.google.com/open?id=1840jC8sBd4_cl9cyzVPNsC8AiHmvQySQ",
      "CCC-GHCBK1-02": "https://drive.google.com/open?id=1nJDbH-a4sza_rHVwj1ivF38sYXKPUlwL",
      "CCC-GHCBK1-03": "https://drive.google.com/open?id=1FKL7y1_05yZD0YiEcZZHnuROT2FEhLK5",
      "CCC-GHCBK1-04": "https://drive.google.com/open?id=1xGYw9_sWzGU3zijojzFnZ_RaxofesDIW",
      "CCC-GHCBK1-05": "https://drive.google.com/open?id=1Tr9azUQdZk4aBeja_lwBERAWKNcM_p9c",
      "CCC-GHCBK1-06": "https://drive.google.com/open?id=1D7AdoMUxdCPMI4pjUXrtRsSqCvFy9CDn",
      "CCC-GHCBK1-07": "https://drive.google.com/open?id=1GNKKZzSyQQMLUVb-bduAa-9rRLSSYxqv",
      "CCC-GHCBK1-08": "https://drive.google.com/open?id=1dVMwHF_-hVFoJMvS02RcILZL3JJ-NUJE",
      "CCC-GHCBK1-09": "https://drive.google.com/open?id=1zlunLNSfnOrCHSPxdEooRfE1rbTppiJ3",
      "CCC-GHCBK1-10": "https://drive.google.com/open?id=1Ta7oJPS4fI3JRhkIWVsAnnbahUZZkE6d",
      "CCC-GLIP-0101": "https://drive.google.com/open?id=10vsingLVoswKLCz2pi218HjHvcOOEyTI",
      "CCC-GLIP-0102": "https://drive.google.com/open?id=17XOTluRFQES70_VoPuzVLAQ12mSXuj0m",
      "CCC-GLIP-0103": "https://drive.google.com/open?id=1usa_wrZQEDKDBnxCc7g8vVwTj9GsjhiH",
      "CCC-GLIP-0201": "https://drive.google.com/open?id=1ad_WPrEkoSR7ZLsNrb2024Z02u04GAv3",
      "CCC-GOC-0101": "https://drive.google.com/open?id=17_smp5VlaWeH_eH7jL7HGefT6DXsf7fr",
      "CCC-GOC-0102": "https://drive.google.com/open?id=1bswluyrQhjVVV3UuK5nlxXj24zGRUPRp",
      "CCC-GOC-0103": "https://drive.google.com/open?id=1Ii6QI2229DZ7vur56HN3LVEgBJONT24X",
      "CCC-GSP-0101": "https://drive.google.com/open?id=1-PQQ74ntjaabbkv_UUMVmX9Q0XvHkNlE",
      "CCC-HAL-01": "https://drive.google.com/open?id=1JBYSUE5gXnxotRc6fQbzZ5CN2c270vw5",
      "CCC-HAL-02": "https://drive.google.com/open?id=14tpH80ArjoU3mdyulQTL7lTe7P2Ctsvi&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-HAL-03": "https://drive.google.com/open?id=14k9g26gOsoPml-FQtZRWHp6ek99HIh7e&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-HATMS01-01": "https://drive.google.com/open?id=1-64UKTYxNkpwkV-mEP8g44iNpu89HNUn",
      "CCC-HATMS01-02": "https://drive.google.com/open?id=1GKbQUrlFAcaJSktyYk5FjD9PpSUZda4k",
      "CCC-HATMS01-03": "https://drive.google.com/open?id=1g3Mb_5q7ppL8pvt5Dl86AgRQAxnJmSiV",
      "CCC-JGD-01": "https://drive.google.com/open?id=199eM9OBh4oJpYqp9zYAJbMpZXlHscZMJ",
      "CCC-JGD-02": "https://drive.google.com/file/d/1MFO9_70Absoi_zT4jS2GvqeuMe5p6hfc/view?usp=share_link",
      "CCC-JGD-03": "https://drive.google.com/file/d/1NSuynvP3mGMvTXDsjHQSQ97KinVPOKrf/view?usp=share_link",
      "CCC-JGD-04": "https://drive.google.com/file/d/1SAVeL8Ip1scoUq2qbCyvHy68A9x4TlPe/view",
      "CCC-KUMORI-0101": "https://drive.google.com/open?id=14owGYBh5yr-MfKV9Yf_yP4cLQgQmFqdd",
      "CCC-KUMORI-0102": "https://drive.google.com/open?id=1Ef0cWUpIFdtrCzSwgtuuqw8TG4OQkgsy",
      "CCC-KUMORI-0204": "https://drive.google.com/open?id=1m8qS89gAcNUs6rRvkFuKwEQrK2NsmTyn",
      "CCC-LINKS-01": "https://drive.google.com/open?id=0B9NR7rHEJNUGMXZzQWk0cFFJNDQ",
      "CCC-LINKS-02": "https://drive.google.com/open?id=0B9NR7rHEJNUGTFg0RGNPY1k3TGs",
      "CCC-MACE-01": "https://drive.google.com/open?id=1ndsAxeXJUvyBNncguG-64ScE4LnfgOko",
      "CCC-MACE-02": "https://drive.google.com/open?id=1Yw3MHOY9WGwq5XbsVPb7kIMTCnCA6xrG",
      "CCC-MACE-03": "https://drive.google.com/open?id=1vu74MNNazno1boowVCB-1Ib0CoAZcDeM",
      "CCC-MCX-01": "https://drive.google.com/open?id=1syOx6QubFX5MtfeYwBXxikogWysRyZPC",
      "CCC-MIND-01": "https://drive.google.com/open?id=16dt-mzTJYTSeITit6hu_zLs9AQsPKyWx",
      "CCC-MIND-02": "https://drive.google.com/open?id=160XiXi57CcPWIueEn211s9GIDmXZrALO",
      "CCC-MIND-03": "https://drive.google.com/open?id=1R3dem56jM0EObssm-zJHQlabvARSxNme",
      "CCC-MMT01-01": "https://drive.google.com/open?id=1WJLdxcF6kiyyQWUl7SgQNzdjP1sVQz03",
      "CCC-MMT01-02": "https://drive.google.com/open?id=13PFShvCaAMxyALo8wHwGI-bNk8KtI0j_",
      "CCC-MMT01-03": "https://drive.google.com/open?id=1x5OlVOKAMy8EG3z5FgIew-0XvE-XyNJd",
      "CCC-MYR-01": "https://drive.google.com/open?id=1aW9QSXdIi3jdiD2gFkGyQEF71mmxY3Ud",
      "CCC-NBDD01-01": "https://drive.google.com/open?id=1ip1iIC7GYS8WaiwsUCzu1x9z3_J8LCeO",
      "CCC-NUKE-0101": "https://drive.google.com/open?id=1wTb2LuvkDc1Y-gKfz-jf_Z4XRhWBRWwW",
      "CCC-NUKE-0102": "https://drive.google.com/open?id=1mHElq8xVROJ0LVcd0tO186SmHJQTnNz-",
      "CCC-ODFC-0101": "https://drive.google.com/open?id=1F9maEjosnPpRIl40dvHjkckEirCWnpsS",
      "CCC-ODFC-0102": "https://drive.google.com/open?id=1yXiYt3ryqvOyLvcXiOSftV0ucoxVIQ2Z",
      "CCC-ODFC-0103": "https://drive.google.com/open?id=1sGWttOwxSIE_8YxMMLvxW7GRIubjGF5b",
      "CCC-ODFC-0201": "https://drive.google.com/open?id=1xBqAr6drGGdmQAHdETLikz0ASsFtieVY",
      "CCC-ODFC-0202": "https://drive.google.com/open?id=1mb0O02rgj7RvXr06BwNeiK9zqUfi2R0C",
      "CCC-ODFC-0203": "https://drive.google.com/open?id=1xcNvaqGPnh4dEuGBcgs9DBTwAeZuS_rS",
      "CCC-ODFC-0301": "https://drive.google.com/open?id=1k3nlmvV3x95-I2YT_TAjjGG1Em13J4tB",
      "CCC-PDXAGE-0101": "https://drive.google.com/open?id=0B9NR7rHEJNUGYUtKWUpaY0xYaUk",
      "CCC-PDXAGE-0201": "https://drive.google.com/open?id=0B9NR7rHEJNUGMGNyTDhUckROZGM",
      "CCC-PHA-01": "https://drive.google.com/open?id=1iFKDQKhzw1faLnlk1rTuOAOn_lh8gjk8",
      "CCC-PRIORY-01": "https://drive.google.com/open?id=1--0MHViNRlA4ys7FhO1irGHRvyX7X8d6",
      "CCC-PRIORY-02": "https://drive.google.com/open?id=139-sxwG7vagq_d5sAdod8MtOUltKg-QY",
      "CCC-PRIORY-03": "https://drive.google.com/open?id=1lxtApW8sQdKEEX9DDP3EgW39FmjO9K0S",
      "CCC-QCC2017": "https://drive.google.com/open?id=0B9NR7rHEJNUGSXdSVFBzVWswNFk",
      "CCC-QCC2018-01": "https://drive.google.com/open?id=1Hpf_BUd5pSS7PKpDFaIKf74koFMLNwCh",
      "CCC-QCC2018-02": "https://drive.google.com/open?id=1Hpf_BUd5pSS7PKpDFaIKf74koFMLNwCh",
      "CCC-ROZK-0101": "https://drive.google.com/open?id=0B9NR7rHEJNUGS1QxNnVkbGJnNzg",
      "CCC-ROZK-0102": "https://drive.google.com/open?id=0B9NR7rHEJNUGZ21CZUV6QlhnNDA",
      "CCC-ROZK-0103": "https://drive.google.com/open?id=0B9NR7rHEJNUGU2NtN0ZSWm5SZW8",
      "CCC-RPR-01": "https://drive.google.com/open?id=1JKgS1EJ9SvMtiruABBXKX8Oi_9hf9atw",
      "CCC-RPSG-01": "https://drive.google.com/open?id=1Mu0ajj1zk1SA0koH6dc2p6mPu8WMp0-m",
      "CCC-SAC-01": "https://drive.google.com/open?id=1F926kQL_e2q6CB34nPfcpgmWM1hUzDcD&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-SAC-02": "https://drive.google.com/open?id=1I6MD2p_QOZNQTdiP91J_KmxY-9FuN5yI",
      "CCC-SAC-03": "https://drive.google.com/open?id=1F2q9ZAPTtuGoQzwkvwFs-jsgyNcNheFg&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-SALT-01-01": "https://drive.google.com/open?id=0B9NR7rHEJNUGblp5bVRPdjZQNGc",
      "CCC-SALT-01-02": "https://drive.google.com/open?id=0B9NR7rHEJNUGOHpUUHB6d2FyS2c",
      "CCC-SALT-01-03": "https://drive.google.com/open?id=0B9NR7rHEJNUGUWt5Ym9Fc0dsQlE",
      "CCC-SALT-02-01": "https://drive.google.com/open?id=1MpGuChtIeCBabhEe-ZtCigzcQYcx6aYb",
      "CCC-SALT-02-02": "https://drive.google.com/open?id=1r9U10u3RZwsPKb7ctan7XdwcfRd9p0a2",
      "CCC-SALT-0205": "https://drive.google.com/open?id=1IXV6AAEW87YTRUxGqr6S6_bbIkaCf2CT",
      "CCC-SCAR01-01": "https://drive.google.com/open?id=14uZe3he7VQ7zGq9IXbEgX019Y0Z_xpWd",
      "CCC-SCAR01-02": "https://drive.google.com/open?id=1_f_HFEyu7YuqKFOBtB2ZdnEgpT8m5l9p",
      "CCC-SCAR02-01": "https://drive.google.com/open?id=1nKs09a2b2kilcD3ei5nblBXVzskenvFi",
      "CCC-SCAR02-02": "https://drive.google.com/open?id=12YLVoG-BQjiLTpzIp5bOADDG7bxenlew",
      "CCC-SFBAY-0101": "https://drive.google.com/open?id=1s0UgLjJ2Sm33MUqcsyM8JFBSRf--iRV6",
      "CCC-SFBAY-0201": "https://drive.google.com/open?id=1TpXMpf0KFzIZrt20Eiq5Pk_y-5kdpNY-",
      "CCC-SFBAY-0202": "https://drive.google.com/open?id=1gYnem6WyxarqhzMv9klVhnW7G54wSisB",
      "CCC-SFBAY-0203": "https://drive.google.com/open?id=1XtMCC2PaT7vUQ2UC6wSQf9nKLbLO1Wiw",
      "CCC-SFBAY-0401": "https://drive.google.com/open?id=1OoPVfZ0zDCGh33MqtcwlcVaOEaBFrksB",
      "CCC-SFBAY-0402": "https://drive.google.com/open?id=1tnfV291XqVZewItNI0WQVix_i_6VRFEG",
      "CCC-SFBAY-0403": "https://drive.google.com/open?id=1__bEyjGiUq3zcGLhZbhjglk-ucUIiTYE",
      "CCC-SHINY-02": "https://drive.google.com/open?id=1zRt3zqfEhoyw89biuh8QSjlTY1HUepOA",
      "CCC-SKULL01-01": "https://drive.google.com/open?id=1FDe_mebywhDcmnld-17NgyNimPNBq4H4&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-SKULL01-02": "https://drive.google.com/open?id=1FQZQkpBBNAooDY8abuV6Twj7T-eDBUjs&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-SKULL01-03": "https://drive.google.com/open?id=1FLLqIHQc6rSaygqzrqtXgyeZq6SAbf58&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-SQC-001": "https://drive.google.com/open?id=1GD7qG1bgNo0Njlq9yc_kB0dNueG1MXRX&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-SQC-0201": "https://drive.google.com/open?id=10QuGMGwH4EDvcB8rYkcOH6Vkxbv6C_KP",
      "CCC-SQC-0202": "https://drive.google.com/open?id=1eIncbM-JLk4dZ5_TtuQMQq6cUWZsNCFB",
      "CCC-SRCC-0101": "https://drive.google.com/open?id=0B9NR7rHEJNUGbjRtWV9qM2JjOGM",
      "CCC-SRCC-0102": "https://drive.google.com/open?id=0B9NR7rHEJNUGNmVMLWtzbGs4Nnc",
      "CCC-SRCC-0103": "https://drive.google.com/open?id=0B9NR7rHEJNUGVEl4NFNqSjN2cUE",
      "CCC-STORM-01": "https://drive.google.com/open?id=1_A6B-tFLl2fPXTmcFP6c-e80EKMXy2Cy",
      "CCC-STORM-02": "https://drive.google.com/open?id=14i4JKFHejXc6DNj3jo8RlTYv8O2QWvD-&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-STS2-1": "https://drive.google.com/open?id=1eaDgAo7w7frYzn7I8aHPXehlqHTY0fJ2",
      "CCC-SVH01-01": "https://drive.google.com/open?id=1czuevVGADuDRYjA10Ne5gSicl8iHmYLF",
      "CCC-SVH01-02": "https://drive.google.com/open?id=1L5p1MQFlpWrOnbbsg1M472JoPcmBwAeT",
      "CCC-SVH01-03": "https://drive.google.com/open?id=1NzCKifiDBG84nlo-I1X-z1aR4dKcTXm9",
      "CCC-TAROT-0101": "https://drive.google.com/open?id=14Mf2HIdMvoCQtiMrkWpKY-U81274b9l_",
      "CCC-TAROT-0102": "https://drive.google.com/open?id=1rfkBvuMTQNBRnFFWJQYw4h_Dws6eeols",
      "CCC-TAROT-0103": "https://drive.google.com/open?id=1wjwdzSup6ThVOJ4z2QB7L11AoFJ614hQ",
      "CCC-TAROT-0104": "https://drive.google.com/open?id=1Um72ea9051tJ2x2ZLD-8GVeu_bcJuQXi",
      "CCC-TAROT-0105": "https://drive.google.com/open?id=1Cpa00_R4EQ8QFLd1tqHFIxtMYyyb3qmn",
      "CCC-TAROT-0106": "https://drive.google.com/open?id=1SEZH1fBKuXG0JQo-VIdSS3p1GrZ1XoRN",
      "CCC-TAROT-0107": "https://drive.google.com/open?id=1KKmnAp63I9JlkKJeIabNVK268eryPd8s",
      "CCC-TAROT-02-01": "https://drive.google.com/open?id=14iYfXdTQ8y8lyupIKJmKUxovF5Hwg6Xm&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "CCC-THENT-0101": "https://drive.google.com/open?id=0B9NR7rHEJNUGRFVTZEpIdVl0SFk",
      "CCC-THENT-0102": "https://drive.google.com/open?id=0B9NR7rHEJNUGOHhjUkZEaTVDRkE",
      "CCC-THENT-0103": "https://drive.google.com/open?id=0B9NR7rHEJNUGOW9rWGpFUEF0T1U",
      "CCC-TRI-01": "https://drive.google.com/open?id=0B9NR7rHEJNUGRUZla3A2SGJsZDg",
      "CCC-TRI-02": "https://drive.google.com/open?id=1pAVmkHMMTn8aKEynDm-i3cVQK9xqwQEs",
      "CCC-TRI-03": "https://drive.google.com/open?id=1-MiTbFGzRGBMeyXkCXW-nFVTeZM5gMfC",
      "CCC-TRI-04": "https://drive.google.com/open?id=1KvbSJ6TOysE30EIyl8ybVX13nyr_lX4_",
      "CCC-TRI-05": "https://drive.google.com/open?id=1Y7D7pWuLVqqF4aBTXSyz2SvRnApQhaRG",
      "CCC-TRI-06": "https://drive.google.com/open?id=1ITi7IvsU_UCdyheqN82nHaut6eimxO3r",
      "CCC-TRI-07": "https://drive.google.com/open?id=1VZ9B3700AznQhWNSYsm796SgiU_DODl8",
      "CCC-TRI-08": "https://drive.google.com/open?id=1TaidgyLVQVeIx8cw8utO461BgEqOo-w3",
      "CCC-TRI-09": "https://drive.google.com/open?id=1Le7pYmtkIxXNFOF15ZXl_TaMrPjoP7ng",
      "CCC-TRI-10": "https://drive.google.com/open?id=1oy8BZPa1l0lYsSvrq6x9mMfBmg-a1sS4",
      "CCC-TRI-11": "https://drive.google.com/open?id=1ZLXNlTKvxS1Ep2Gdt-9PBPHR6Djj1Apy",
      "CCC-TRI-12": "https://drive.google.com/open?id=1drp0IJtrHeetNXxqjFHJoRSdxEHiwLYh",
      "CCC-TRI-13": "https://drive.google.com/open?id=1jlPkxg1ftYcLrf6HibEed8Nc1RGJ2R1L",
      "CCC-TRI-14": "https://drive.google.com/open?id=1fa8Bl1lHuCX_OpKuP5eQUudSfzK71iJp",
      "CCC-TRI-15": "https://drive.google.com/open?id=18Bbj3SfRpthS7hf18EzP3ZmBiI7H3wfl",
      "CCC-TRI-16": "https://drive.google.com/open?id=1nyK3vuKFNuUZigZFlJuQsnBXzPFDzdKX",
      "CCC-TRI-17": "https://drive.google.com/open?id=1s8jpXV2avia-8zmzV0YHNNGDZmLzKkn7",
      "CCC-TRI-18": "https://drive.google.com/open?id=1rIOta6QO7oOb7yQYl2XaYHCCYYVsXzJv",
      "CCC-TRI-19": "https://drive.google.com/open?id=1ptwsFFm5HD2Jn-kJqaWXOJmY6Rd96C8l",
      "CCC-TRI-22": "https://drive.google.com/open?id=1opIadCDa1u5BYVqEhclFbJ0mQ0rnVyfW",
      "CCC-TRI-23": "https://drive.google.com/open?id=1p-IzrEJl53fx0VY2uJ-y6rYxJ83b_yQs",
      "CCC-TRI-24": "https://drive.google.com/open?id=1XidRsf-x4Si--uffZ-3IckOcv_vkuud2",
      "CCC-TRI-25": "https://drive.google.com/open?id=1wkcB-fYKhXl-5mV-Pu4c4IdKF80nYe4b",
      "CCC-TRI-29": "https://drive.google.com/open?id=1P1PJFwfKxczRtZ8xfKcsLb-BfVV5DDL2",
      "CCC-TRI-30": "https://drive.google.com/open?id=1BWniev7NyUuNVeZ5XAwh0iXiW84lGWQh",
      "CCC-TRI-31": "https://drive.google.com/open?id=18ZQ7aaVEvGCCOslhHcQY7CWunRZJqnSU",
      "CCC-TRI-32": "https://drive.google.com/open?id=11SV0k2KMcG7E2WRqnWEaEHi_OlwnowgE",
      "CCC-TRI-33": "https://drive.google.com/open?id=1lbW4Ri_lYYIjFtl--keJD2yHklbNYDti",
      "CCC-TRI-34": "https://drive.google.com/open?id=1UjOExsDBM0iKi3ngjWbw6PWpE_0JYy1b",
      "CCC-UCON-01": "https://drive.google.com/open?id=0B9NR7rHEJNUGQ2ptMEUwT3kzNTQ",
      "CCC-UK-1": "https://drive.google.com/open?id=1tM6o6-GthrxiT-v6xrRJqOrtL7Sk3Qp2",
      "CCC-UK-2": "https://drive.google.com/open?id=1AJYTql4jCyyv_1GMyGqwS02xjTkpo_5E",
      "CCC-WWC-01": "https://drive.google.com/open?id=1kfI-3Dkd9ZagTqLIurnEzsHX47X2M5yi",
      "CCC-WWC-02": "https://drive.google.com/open?id=1jg6Spv6rGkD2LXxCYcCQHLZvSTMHyAMq",
      "CCC-WWC-03": "https://drive.google.com/open?id=1Ra33oSqjqdq8jqK5uGaCCQQRzIRzwtaJ",
      "CCC-WWC-04": "https://drive.google.com/open?id=1vxaqMEYv6HnS3LqF6ajWPsx6u5FUJJAt",
      "CCC-YLRA-01": "https://drive.google.com/open?id=0B9NR7rHEJNUGemVWUndmTGlSc3c",
      "CCC-YLRA-02": "https://drive.google.com/open?id=0B9NR7rHEJNUGZzJjeDE2LXFvbUE",
      "CCC-YLRA-03": "https://drive.google.com/open?id=0B9NR7rHEJNUGclpDb0QtNUM3WlU",
      "CCC-ZIEGE-01": "https://drive.google.com/open?id=1bn_Uu5OqEvWEqQk6CpR9RKHHxJyXHoxH",
      "CCC-ZIEGE-02": "https://drive.google.com/open?id=1QllIWomNLTZ99SmEusaQgv-ftxbbN08u",
      "CCC-ZIEGE-03": "https://drive.google.com/open?id=1629zGNOQY6242h57ezJYCuVazXUs3nMl",
      "CCC-ZIEGE-04-01": "https://drive.google.com/open?id=1LX5TgA4Pdj6h2XZuzuHWhsVQVhA4bInB",
      "CCC-ZIEGE-04-02": "https://drive.google.com/open?id=10ol0lODfydjMqC2GVKEcA2jb6WrLXMAu",
      "DDAL-CGB": "https://drive.google.com/open?id=1t5_kmKJKJclMBOZm73rPuqTLNnzuzh2Y&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "DDAL-DRW01": "https://drive.google.com/file/d/1FE5kMgdKtRoKyltsdzYdi3c0FoPGNfsZ/view?usp=sharing",
      "DDAL-DRW02": "https://drive.google.com/file/d/1KeXLfLTN5Bf3altbGiy4R-4hvrZ8fQF0/view?usp=sharing",
      "DDAL-DRW03": "https://drive.google.com/file/d/1XKZhSayQEOvHJF1o4miZ9LG5dNnmtodL/view?usp=sharing",
      "DDAL-DRW04": "https://drive.google.com/file/d/11ZcD6FX9V3wooA5FSFlz884sBahSu2GU/view?usp=sharing",
      "DDAL-DRW05": "https://drive.google.com/file/d/11ZcD6FX9V3wooA5FSFlz884sBahSu2GU/view?usp=sharing",
      "DDAL-DRW06": "https://drive.google.com/file/d/1_Bp80NUlVJMk6_FatsU5SO45esercj4b/view?usp=sharing",
      "DDAL-DRW07": "https://drive.google.com/file/d/1hEhNqZZFMmnH7sbARFk8q0VXKCc2Sks9/view?usp=sharing",
      "DDAL-DRW08": "https://drive.google.com/file/d/1xElklH2-FD9uEnxSHSaSCaQ7Cw2_pBst/view?usp=sharing",
      "DDAL-DRW09": "https://drive.google.com/file/d/1ZsLplRDPCg2Yshh9YeB6u7hOTHghHKEJ/view?usp=sharing",
      "DDAL-DRW10": "https://drive.google.com/file/d/1srZwzdwwuUR3olR1pZznHr1QgKROT1od/view?usp=sharing",
      "DDAL-DRW11": "https://drive.google.com/file/d/1eHxQbOqXZdRGhZiXORPpRXUg-Ku2N0CJ/view?usp=sharing",
      "DDAL-DRW12": "https://drive.google.com/file/d/1eX1LahPLcZh23JLcNAA5lhOJ3ptiaygp/view?usp=sharing",
      "DDAL-DRW13": "https://drive.google.com/file/d/1_m_LmFah92mNC8yaJWHnwk8sLJmlSgVj/view?usp=sharing",
      "DDAL-DRW14": "https://drive.google.com/file/d/1FmciT2Fdax_SrCRT6yCvpE7BntNJNlSr/view?usp=sharing",
      "DDAL-DRW15": "https://drive.google.com/file/d/10KPBUPei3oi0LuIOCBnLyFPoIrQKjeJY/view?usp=sharing",
      "DDAL-DRW16": "https://drive.google.com/file/d/1_46D2X_fPTxFszDEygbn4Z6kTs6mA_9D/view?usp=sharing",
      "DDAL-DRW17": "https://drive.google.com/file/d/1mAwfDjTfxtgkptwAyehVHVfSB0ZV8C2O/view?usp=sharing",
      "DDAL-DRW18": "https://drive.google.com/file/d/1fpm7dE1Q9CArdyjafOOvF5BcAdvQTlmY/view?usp=sharing",
      "DDAL-DRW19": "https://drive.google.com/file/d/1Jsy8YzkqSo5WQplm39qv2yxQsGoBB_xt/view?usp=sharing",
      "DDAL-DRW20": "https://drive.google.com/file/d/17Gj6WrAcHpmkaJF4EUu40r2EtyUrhfBj/view?usp=sharing",
      "DDAL-EB-01": "https://drive.google.com/open?id=1tlVqBEZqF0OAqRBvFeqmJdd5zPBCIRBY",
      "DDAL-EB-02": "https://drive.google.com/open?id=1h-XJNoClW-57_kK_PbU3LEsctyDX4mA4",
      "DDAL-EB-03": "https://drive.google.com/open?id=1NsqA97XNBnMM8Y-0K5k-OLIA2yYr5KmI",
      "DDAL-EB-04": "https://drive.google.com/open?id=1Lda47dN9SeRTCuxCsEssRaWO91B_btfx",
      "DDAL-EB-05": "https://drive.google.com/open?id=1P6E66Zy0gF-jeG4GLtSPD43jY8jrnN7Y&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "DDAL-EB-06": "https://drive.google.com/open?id=1eeGWjz6vu0Vf6tCKtfMm3FmcWrQbCfcv&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "DDAL-EB-07": "https://drive.google.com/open?id=1G61cLuNbOXTztHM7T7DI4anWOl8qcz0J&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "DDAL-EB-XX": "https://drive.google.com/open?id=1ctoftIlnpw6Y7gyfoohRg3VAMHOfZkqa",
      "DDAL-EBEP-01": "https://drive.google.com/open?id=1bdcnBniCSxtegUUBsgLhtn5_rzxzUlCx",
      "DDAL-ELW00": "https://drive.google.com/open?id=1khUmEcL2VHdanaN-v2N4G8nd7r3wL55-",
      "DDAL-ELW01": "https://drive.google.com/open?id=1z-Ni9CyzU0mV9vdHd4OdB6th9wjm2v45",
      "DDAL-ELW02": "https://drive.google.com/open?id=1s1aw6yTqp0rk7HiA3Jp1866NZcmwT8zh",
      "DDAL-ELW03": "https://drive.google.com/open?id=16IC_reSI7RJQ3ljryop2A_Q9WSrGJiLj",
      "DDAL-ELW04": "https://drive.google.com/open?id=1pCjh9cYbdqT-RT7buNFhk8Cgdw7zaphQ",
      "DDAL-ELW05": "https://drive.google.com/open?id=19of1Blgq14SbWyEHTRGBKqgkV6zaModl",
      "DDAL-ELW06": "https://drive.google.com/open?id=1cDit8hUrpkMNoEs963eOSV3435_CvSG0",
      "DDAL-ELW07": "https://drive.google.com/open?id=1TfjHBtsg7hSagXBpAi8L9X4rEnBK9jHI",
      "DDAL-ELW08": "https://drive.google.com/open?id=1oNs7UGkNYQsTSqhsxFATBG-A5vicbMd4",
      "DDAL-ELW09": "https://drive.google.com/open?id=1rivaRLG9TS5SOKB1xNdudLbNjqcCmWMm",
      "DDAL-ELW10": "https://drive.google.com/open?id=1BzvzwJn69imqxAN0eQ6TVPAT4OBTtyGY",
      "DDAL-ELW11": "https://drive.google.com/open?id=1KXfsdXUQIQp_Af6tPcQwd6Ck2f9wyaFv",
      "DDAL-OPEN-2016": "https://drive.google.com/open?id=1pAS0Irm7PG1bEBHYE3QS2SZFHlwixz_b",
      "DDAL-OPEN-2017": "https://drive.google.com/open?id=1CiIg6DnMGg1dAX_GgcNgTvXoNWzWbO0p",
      "DDAL-OPEN-2018": "https://drive.google.com/open?id=1Cts7TFdGZRqK6ysn1ZQ7YGpdmxgDCHWF",
      "DDAL-OPEN-2019": "https://drive.google.com/open?id=1nonVtVjIcExwCUjvfbiQUKbyfR7MyNTF",
      "DDAL-WGE-01": "https://drive.google.com/open?id=1_-mPuLnjvviDFhfAWoEB6Ce1tmuNZYRY&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "DDAL00-??": "https://drive.google.com/open?id=13oTmOTGgGOhUTXZRthRvTJc-VEEMKYKy",
      "DDAL00-01": "https://drive.google.com/open?id=0B9NR7rHEJNUGcWxhMXlJbmlQTGM",
      "DDAL00-02-A": "https://drive.google.com/open?id=1gr3Mvt3DyqHlTmN-wCmSs9XB7wR2MRoU",
      "DDAL00-02-B": "https://drive.google.com/open?id=1gr3Mvt3DyqHlTmN-wCmSs9XB7wR2MRoU",
      "DDAL00-02-C": "https://drive.google.com/open?id=1gr3Mvt3DyqHlTmN-wCmSs9XB7wR2MRoU",
      "DDAL00-02-D": "https://drive.google.com/open?id=1gr3Mvt3DyqHlTmN-wCmSs9XB7wR2MRoU",
      "DDAL00-02-E": "https://drive.google.com/open?id=1gr3Mvt3DyqHlTmN-wCmSs9XB7wR2MRoU",
      "DDAL00-02-F": "https://drive.google.com/open?id=1gr3Mvt3DyqHlTmN-wCmSs9XB7wR2MRoU",
      "DDAL00-03": "https://drive.google.com/open?id=1Hk1deCRuwwQ8Xkp-9dgdTbnezi_v-3JK",
      "DDAL00-04": "https://drive.google.com/open?id=199ErCyy6Y69GcZdJlnqXKeSmdxXtw9Q2",
      "DDAL00-05": "https://drive.google.com/open?id=1tWrL-LRl9z-b7IqHms_OBqWTehwfB-CK",
      "DDAL00-06": "https://drive.google.com/open?id=1gt3KE7va9veH-BNQr4ZqtNQahxYpCeaD",
      "DDAL00-07": "https://drive.google.com/open?id=1ixIMVzrhrZEoEkCKXZbpywbfDWqZAg4-",
      "DDAL00-08": "https://drive.google.com/open?id=1eQZvdYrXjQ8Gb33Q81sB66X-CXwc2pbb",
      "DDAL00-09": "https://drive.google.com/open?id=1BCan7cR6bDBVbFFAtzPAPAlk_qrWvoHt",
      "DDAL00-10": "https://drive.google.com/open?id=1Gaq_1B2mpIDRsV8_4d-26hY7crXRXxz3",
      "DDAL00-11": "https://drive.google.com/open?id=1QAw-j9GNBIbSAzI7g8xtIAn7uvG9ILp-",
      "DDAL00-12": "https://drive.google.com/open?id=1oofcL46KMXRfR-LFbRwSj2DHNfOoWWIC",
      "DDAL04-01": "https://drive.google.com/open?id=0B9NR7rHEJNUGckkyaUpEWl9jenc",
      "DDAL04-02": "https://drive.google.com/open?id=0B9NR7rHEJNUGb015eE9NSEUzcG8",
      "DDAL04-03": "https://drive.google.com/open?id=0B9NR7rHEJNUGNlROeHR3QjdkTnM",
      "DDAL04-04": "https://drive.google.com/open?id=0B9NR7rHEJNUGMU1lR1JFQnRFTWs",
      "DDAL04-05": "https://drive.google.com/open?id=0B9NR7rHEJNUGdXhOenJPWUFtYzg",
      "DDAL04-06": "https://drive.google.com/open?id=0B9NR7rHEJNUGNUYxYXdZTnRQLUU",
      "DDAL04-07": "https://drive.google.com/open?id=0B9NR7rHEJNUGQmF1R2ZKSER0S2M",
      "DDAL04-08": "https://drive.google.com/open?id=0B9NR7rHEJNUGVEpGVE1OQ3VsRXc",
      "DDAL04-09": "https://drive.google.com/open?id=0B9NR7rHEJNUGb0JTbE5PdjRTdDA",
      "DDAL04-10": "https://drive.google.com/open?id=0B9NR7rHEJNUGZTZTb25tc2xoak0",
      "DDAL04-11": "https://drive.google.com/open?id=0B9NR7rHEJNUGNE8yN2thbkFzbWs",
      "DDAL04-12": "https://drive.google.com/open?id=0B9NR7rHEJNUGem1ZZXRvNkN1MHc",
      "DDAL04-13": "https://drive.google.com/open?id=0B9NR7rHEJNUGa1BGLWd0bUhhTzA",
      "DDAL04-14": "https://drive.google.com/open?id=0B9NR7rHEJNUGS2M5TzhXblJHcXc",
      "DDAL05-01": "https://drive.google.com/open?id=0B9NR7rHEJNUGWkJMeXYwVGN2LWc",
      "DDAL05-02": "https://drive.google.com/open?id=0B9NR7rHEJNUGWGJQQzhOTk1qemM",
      "DDAL05-03": "https://drive.google.com/open?id=0B9NR7rHEJNUGMnBhTDBQOEhOamM",
      "DDAL05-04": "https://drive.google.com/open?id=0B9NR7rHEJNUGU2lLUDVaNTBRQTg",
      "DDAL05-05": "https://drive.google.com/open?id=0B9NR7rHEJNUGR0NEUkNNamJ0ZHc",
      "DDAL05-06": "https://drive.google.com/open?id=0B9NR7rHEJNUGUHFGSWRtZFA1Qjg",
      "DDAL05-07": "https://drive.google.com/open?id=0B9NR7rHEJNUGSnl0NVVzMm5FLXc",
      "DDAL05-08": "https://drive.google.com/open?id=0B9NR7rHEJNUGcUdsOS1lYmlwZkU",
      "DDAL05-09": "https://drive.google.com/open?id=0B9NR7rHEJNUGRURGNUZnaWtmUTQ",
      "DDAL05-10": "https://drive.google.com/open?id=0B9NR7rHEJNUGaWhGR1o5WHI4QmM",
      "DDAL05-11": "https://drive.google.com/open?id=0B9NR7rHEJNUGV3ZmSUhhQWtmWE0",
      "DDAL05-12": "https://drive.google.com/open?id=0B9NR7rHEJNUGY19KdUpRNmlWc0k",
      "DDAL05-13": "https://drive.google.com/open?id=0B9NR7rHEJNUGTWpUbENET0Yxd1U",
      "DDAL05-14": "https://drive.google.com/open?id=0B9NR7rHEJNUGc1JKcEI3TkxvNk0",
      "DDAL05-15": "https://drive.google.com/open?id=0B9NR7rHEJNUGZ1A5Zl96ajQydnc",
      "DDAL05-16": "https://drive.google.com/open?id=0B9NR7rHEJNUGOVR0cUp0TEJ6eEU",
      "DDAL05-17": "https://drive.google.com/open?id=0B9NR7rHEJNUGLVJ6RmVOM1FoN1U",
      "DDAL05-18": "https://drive.google.com/open?id=0B9NR7rHEJNUGLUV4X1EyWmhocHM",
      "DDAL05-19": "https://drive.google.com/open?id=0B9NR7rHEJNUGb1JFajVxSGk5ams",
      "DDAL06-01": "https://drive.google.com/open?id=0B9NR7rHEJNUGbXE5NzJINjZPRWc",
      "DDAL06-02": "https://drive.google.com/open?id=0B9NR7rHEJNUGVDVoMW5OS2NLLTA",
      "DDAL06-03": "https://drive.google.com/open?id=0B9NR7rHEJNUGbXE5NzJINjZPRWc",
      "DDAL07-01": "https://drive.google.com/open?id=0B9NR7rHEJNUGYVRoeXBnc2VDbW8",
      "DDAL07-02": "https://drive.google.com/open?id=0B9NR7rHEJNUGYjgtMGVSUlpWc0k",
      "DDAL07-03": "https://drive.google.com/open?id=1pOwXmnjDJ0vYNbY6CBLczflNCcRvPYr4",
      "DDAL07-04": "https://drive.google.com/open?id=1S9bSEvJ4rnG8Hmrzg3e4Gxkn_s9iv2b-",
      "DDAL07-05": "https://drive.google.com/open?id=1_-Ow_-DJPW_znlBT673grNIxviBfLTbF",
      "DDAL07-06": "https://drive.google.com/open?id=1NMzW_eC-E7elRLRR5EL24fYj7NuH61Du",
      "DDAL07-07": "https://drive.google.com/open?id=1O_Jn1gUoGF_Q5FIkZ_bZru0V-jKUwaTn",
      "DDAL07-08": "https://drive.google.com/open?id=19CuIwF28WUAIQ53hezIl8XCdwPlHvtUw",
      "DDAL07-09": "https://drive.google.com/open?id=1X8bPEMDRb5wX2o6fcXqE-ZhPTL2RyRWn",
      "DDAL07-10": "https://drive.google.com/open?id=1SjFH4HL4MS06wq0lSqJoXh-8RiXE4yQr",
      "DDAL07-11": "https://drive.google.com/open?id=1qmSuEC8cSgHRm29fB2OFEMHG59gIGIa9",
      "DDAL07-12": "https://drive.google.com/open?id=1n-HkDR8vi8Y8NSOSw43LOLUrLYUSKLxO",
      "DDAL07-13": "https://drive.google.com/open?id=1E0mXsVfldIplMUNds24MJXiVaOxb_MNb",
      "DDAL07-14": "https://drive.google.com/open?id=1BdHjdIUMxJ7t8fKTARpIh-8n2NyBmZHn",
      "DDAL07-15": "https://drive.google.com/open?id=1j8T5KuU85dAvWV8fW9HzybShmgtJLn1H",
      "DDAL07-16": "https://drive.google.com/open?id=1CKDTU-q0aMCeXkUFbrvaLDcCipC9SIUf",
      "DDAL07-17": "https://drive.google.com/open?id=1rGRoRkNQMH8y7bWsezg-BMbyK3dw19o-",
      "DDAL07-18": "https://drive.google.com/open?id=1gjck7Uwo2aCqBiXwNYCTEshYrFtaz8UC",
      "DDAL08-00": "https://drive.google.com/open?id=12TDqX3wTi7xEyQSVNQ7Y6UutIcI-NxOT",
      "DDAL08-01": "https://drive.google.com/open?id=1qO1MCWJUENNHlzxiroy_tE3NsX_3yRya",
      "DDAL08-02": "https://drive.google.com/open?id=1K5zP6hwjvhnY625wRjB5-t58Lpt8L1mY",
      "DDAL08-03": "https://drive.google.com/open?id=1tfYeN7Qglh6lhXpMQQTsFDAl8JMy1vhS",
      "DDAL08-04": "https://drive.google.com/open?id=11FCDMn60dpPPcDCbR9j4vnCgMcSLKQ-t",
      "DDAL08-05": "https://drive.google.com/open?id=1zQIo1-Ol8qTdldtJ-sSWj7m575I1bf-h",
      "DDAL08-06": "https://drive.google.com/open?id=1hBGlE63XC9o6rs34hdl2odPDMqvIISEm",
      "DDAL08-07": "https://drive.google.com/open?id=113NHUurVlFMQAFrH6L-k6PNYb1Dzf8Ol",
      "DDAL08-08": "https://drive.google.com/open?id=1cdh_DterPr3d8T3TU3uI3jblRPrCReCW",
      "DDAL08-09": "https://drive.google.com/open?id=1rRPsuZ63RnmXY-S4oEcwCns00nd9uzTq",
      "DDAL08-10": "https://drive.google.com/open?id=1d3CPUcfN_6tWFdwXqVfjkP3s_Dkb327E",
      "DDAL08-11": "https://drive.google.com/open?id=1a1gKyUAgmqKIrg0KX0EYMy6hOTkk7dFE",
      "DDAL08-12": "https://drive.google.com/open?id=1R2PUeaAmhxHCvUFA5C2AqSm5JFdV9xeU",
      "DDAL08-13": "https://drive.google.com/open?id=1nFnZNZyoOB4gCTv-Y-rDfV01vh5jhjTg",
      "DDAL08-14": "https://drive.google.com/open?id=1Pxy6_mwJc3_2cNBk6QTMtceSwxn8mkuA",
      "DDAL08-15": "https://drive.google.com/open?id=1AAqOv2cDOJzNkYwMt8A1aTDGHFZ_mbeN",
      "DDAL08-16": "https://drive.google.com/open?id=1OcbKQ_5S_2kOYspOGfOQ6m9p2DDOMKXQ",
      "DDAL08-17": "https://drive.google.com/open?id=1jn8LABZMsuspLTKHrHRo6XdLGZa2Hk0b",
      "DDAL08-18": "https://drive.google.com/open?id=1YPL1gUpvMXBNXY0fNPSN5niVYYJRQ9Y5",
      "DDAL09-01": "https://drive.google.com/open?id=18ppRX4Q1538xXBKqasgc1yI-vV6jokMc",
      "DDAL09-02": "https://drive.google.com/open?id=1nI96VbsoabNzV2z3J78BJA7wNMGZxEFr",
      "DDAL09-03": "https://drive.google.com/open?id=1gWYJt6pvx_T7NwFNDIkddNEYxmvkdvmM",
      "DDAL09-04": "https://drive.google.com/open?id=1OJrGFBttwViGE6Lp2mfDJ-3kfaRNy4Tj",
      "DDAL09-05": "https://drive.google.com/open?id=1lTdOxdqVQoZGjsNoFMWPO3RtwWYusrJI",
      "DDAL09-06": "https://drive.google.com/open?id=1lTdOxdqVQoZGjsNoFMWPO3RtwWYusrJI",
      "DDAL09-07": "https://drive.google.com/open?id=1zIpkWAs36baQ8qjSFCvdt7d7VTCAUKhR",
      "DDAL09-08": "https://drive.google.com/open?id=1lQIdyhnRgG_qDZKxqanyKFQ0s9ATi9Cv",
      "DDAL09-09": "https://drive.google.com/open?id=1zZqCixglRt3sV_vwAOut_n0lhbuwQJ7t",
      "DDAL09-10": "https://drive.google.com/open?id=1YzvG243agbjiCOI2vl-0V4WArFt0MYG3",
      "DDAL09-11": "https://drive.google.com/open?id=1n14yuYzIqTToV0_3Des0_9aXrDS10-RO",
      "DDAL09-12": "https://drive.google.com/open?id=1mB3PHJvU2kWNv-tR7BjUDjJIC_z9qRnZ",
      "DDAL09-13": "https://drive.google.com/open?id=1BsPb2l1ghUVAocKAK4K_9GLuz4heDQUd",
      "DDAL09-14": "https://drive.google.com/open?id=1aGebEJVq18YwqGJHg3Myo2bAgvKvH1qu",
      "DDAL09-15": "https://drive.google.com/file/d/1ppn9QM0QVi9WPMoRIFh0wMRLFWiwGSuM/view?usp=sharing",
      "DDAL09-16": "https://drive.google.com/file/d/1WdnUe_cZuSlfV36FoVIOEmzl1zUqlnXq/view?usp=sharing",
      "DDAL09-17": "https://drive.google.com/file/d/1ADpxVzCvTCpDi2ag90W0A5FDhhLMKP_B/view?usp=sharing",
      "DDAL09-18": "https://drive.google.com/file/d/1-g-m5O9NsfOT__wFppBh9tQK-3yJSBPv/view?usp=sharing",
      "DDAL09-19": "https://drive.google.com/file/d/1xEv6Smln8BlYXrEmygOJ42Hx5IVN2jQI/view?usp=sharing",
      "DDAL09-20": "https://drive.google.com/file/d/1SjPlArasbAkyC4JQluz5sXuOdp81MNEh/view?usp=sharing",
      "DDALCA-01": "https://drive.google.com/open?id=107kiGguHZ0kkt1oV3KLHsHRV9XwfjBI2",
      "DDALCA-02": "https://drive.google.com/open?id=1CJBYOgnByMmqMpp_LTFZKDcyJ3Rum2NT",
      "DDEP-DRW01": "https://drive.google.com/open?id=1MmNE2rHqLEisvqO5T5vQ4m8AsJN75Inx",
      "DDEP00-01": "https://drive.google.com/open?id=1vALSfdNi4OBbnro5OY2lUqdEHPUJtNGK",
      "DDEP05-01": "https://drive.google.com/open?id=1KiGpqJLqFL94Urvvcu_XU7lV0P3rEdlu",
      "DDEP05-02": "https://drive.google.com/open?id=1YXsbpwfp47oriADcsHOaadYDj47K25yV",
      "DDEP06-01": "https://drive.google.com/open?id=1um0uu4xS7wFzghdhzf2zf4qDNSeonf-L",
      "DDEP06-02": "https://drive.google.com/open?id=1mcgge0SarcoNlZhTWBt7DsqVTLc5Bcfq",
      "DDEP06-03": "https://drive.google.com/open?id=1p6A0MVUNWoTKyzg7xIKNoRpViXGgxFEo",
      "DDEP07-01": "https://drive.google.com/open?id=0B9NR7rHEJNUGMXl5WW1yUDRMaFk",
      "DDEP07-02": "https://drive.google.com/open?id=1gr97Oam6c5oP07FC3GC0OGf1NJkQLd82",
      "DDEP08-01": "https://drive.google.com/open?id=1-Ahq62nsmxodCgTrikCPNLb7QFfP9LbC",
      "DDEP08-02": "https://drive.google.com/open?id=1vR-d6_wy9v50PcUOg37zYi1DfEKphDOF",
      "DDEP09-01": "https://drive.google.com/open?id=1t2F2V9UTKE4UJkvDMhL_6d3Z9E5yNlzl",
      "DDEP09-02": "https://drive.google.com/open?id=1Cj0hJRnD7YTZwwlaEf313rwy7baCiw7j",
      "DDEP09-03": "https://drive.google.com/open?id=1g1NnEfqZr5egSguRGLnjA7B9LtT03j0n",
      "DDEP1": "https://drive.google.com/open?id=0B9E-VnDwJVBSUWVEZ1FUSDJId2c",
      "DDEP2": "https://drive.google.com/open?id=1E7Kfswa0a-_SGcUmLIwCu0LICGfHkcFK",
      "DDEP3": "https://drive.google.com/open?id=1Qr4I_BCjrLvjQxpv_FiCIaCm6H_F-cUG",
      "DDEP4": "https://drive.google.com/open?id=1bVauqQfwYXErD8McAXC6BfxAAGAIwaZj",
      "DDEX01-01": "https://drive.google.com/open?id=0B9NR7rHEJNUGY0o1eU1na3Z2NDA",
      "DDEX01-02": "https://drive.google.com/open?id=0B9NR7rHEJNUGMUxqNmRFM1ZKODg",
      "DDEX01-03": "https://drive.google.com/open?id=0B9NR7rHEJNUGWEdQVDNjUXp2eUE",
      "DDEX01-04": "https://drive.google.com/open?id=0B9NR7rHEJNUGaFJZNFpoSEhOR0U",
      "DDEX01-05": "https://drive.google.com/open?id=0B9NR7rHEJNUGVDZVc1B0Ujhmb00",
      "DDEX01-06": "https://drive.google.com/open?id=0B9NR7rHEJNUGLWpiaGdEcGRCZWM",
      "DDEX01-07": "https://drive.google.com/open?id=0B9NR7rHEJNUGQUZlcGpLQVhRN1U",
      "DDEX01-08": "https://drive.google.com/open?id=0B9NR7rHEJNUGd052Qi14cFlMekk",
      "DDEX01-09": "https://drive.google.com/open?id=0B9NR7rHEJNUGVEtnSTFZcXFfOU0",
      "DDEX01-10": "https://drive.google.com/open?id=0B9NR7rHEJNUGLXcwTjhnaHVhSFk",
      "DDEX01-11": "https://drive.google.com/open?id=0B9NR7rHEJNUGb25BRWZ4cXBfWmc",
      "DDEX01-12": "https://drive.google.com/open?id=0B9NR7rHEJNUGeDZzOVhkZ3Zuclk",
      "DDEX01-13": "https://drive.google.com/open?id=0B9NR7rHEJNUGYVZTU0JuYXowX0k",
      "DDEX01-14": "https://drive.google.com/open?id=0B9NR7rHEJNUGR01RMFRvbzlIUGs",
      "DDEX02-01": "https://drive.google.com/open?id=0B9NR7rHEJNUGOGQ5SV9sS0xSQjA",
      "DDEX02-02": "https://drive.google.com/open?id=0B9NR7rHEJNUGRkRLUnFrM1J1NDg",
      "DDEX02-03": "https://drive.google.com/open?id=0B9NR7rHEJNUGamFSd25jcWtKMFk",
      "DDEX02-04": "https://drive.google.com/open?id=0B9NR7rHEJNUGTkJZMkJqWWNMSjg",
      "DDEX02-05": "https://drive.google.com/open?id=0B9NR7rHEJNUGZWdoQzB2V1Y5MHc",
      "DDEX02-06": "https://drive.google.com/open?id=0B9NR7rHEJNUGOHZFMkpFc2pPdFk",
      "DDEX02-07": "https://drive.google.com/open?id=0B9NR7rHEJNUGTGZjSkROWExBRU0",
      "DDEX02-08": "https://drive.google.com/open?id=0B9NR7rHEJNUGOUQtM0R1dHZjc28",
      "DDEX02-09": "https://drive.google.com/open?id=0B9NR7rHEJNUGLWNubFRURTUwUEk",
      "DDEX02-10": "https://drive.google.com/open?id=0B9NR7rHEJNUGRlFnZ2FjQUV0bVE",
      "DDEX02-11": "https://drive.google.com/open?id=0B9NR7rHEJNUGaFlENHFmVjJ1dWs",
      "DDEX02-12": "https://drive.google.com/open?id=0B9NR7rHEJNUGSFV0OC1iRENjVjg",
      "DDEX02-13": "https://drive.google.com/open?id=0B9NR7rHEJNUGbHEwczJiRHp1N1U",
      "DDEX02-14": "https://drive.google.com/open?id=0B9NR7rHEJNUGckdiTjNtRHRpRzg",
      "DDEX02-15": "https://drive.google.com/open?id=0B9NR7rHEJNUGTTllQmt1UzA0ZXM",
      "DDEX02-16": "https://drive.google.com/open?id=0B9NR7rHEJNUGcXgycllHM1JpbUE",
      "DDEX03-01": "https://drive.google.com/open?id=0B9NR7rHEJNUGbXZld29NTGNubW8",
      "DDEX03-02": "https://drive.google.com/open?id=0B9NR7rHEJNUGNERqVk91bmtoWGc",
      "DDEX03-03": "https://drive.google.com/open?id=0B9NR7rHEJNUGY2lfLVY4V1YyMEE",
      "DDEX03-04": "https://drive.google.com/open?id=0B9NR7rHEJNUGS2ZrQi15Z0dWOHc",
      "DDEX03-05": "https://drive.google.com/open?id=0B9NR7rHEJNUGYUFJckJaTlpzRms",
      "DDEX03-06": "https://drive.google.com/open?id=0B9NR7rHEJNUGTDI3QmRUaGhud2M",
      "DDEX03-07": "https://drive.google.com/open?id=0B9NR7rHEJNUGaGRwYkpTYlJUS2s",
      "DDEX03-08": "https://drive.google.com/open?id=0B9NR7rHEJNUGQVpDb1FlYW5RbXc",
      "DDEX03-09": "https://drive.google.com/open?id=0B9NR7rHEJNUGT1B0WHM5Mzl0Q3M",
      "DDEX03-10": "https://drive.google.com/open?id=0B9NR7rHEJNUGZlVkeXRWYXhyaVE",
      "DDEX03-11": "https://drive.google.com/open?id=0B9NR7rHEJNUGTmczaVpZRGo2ZHc",
      "DDEX03-12": "https://drive.google.com/open?id=0B9NR7rHEJNUGUkdfNDdLaUdLeXc",
      "DDEX03-13": "https://drive.google.com/open?id=0B9NR7rHEJNUGckl5cGRpOFM5clE",
      "DDEX03-14": "https://drive.google.com/open?id=0B9NR7rHEJNUGYmhlbC0zVmk0UGM",
      "DDEX03-15": "https://drive.google.com/open?id=0B9NR7rHEJNUGRE9RNzk5WmNtN1k",
      "DDEX03-16": "https://drive.google.com/open?id=0B9NR7rHEJNUGb1RnMlVIX1lScWc",
      "DDHC-CoS": "https://drive.google.com/open?id=0B9NR7rHEJNUGbUJrSVYtYmJsenM",
      "DDHC-HotDQ": "https://drive.google.com/open?id=0B9NR7rHEJNUGZl9kQm9QaHFtLUU",
      "DDHC-LMoP": "https://drive.google.com/open?id=0B9NR7rHEJNUGdWxjRHI1VUtKa0U",
      "DDHC-LR": "https://drive.google.com/open?id=1Snf69CXjYojHjoxeYk5csCzyFGNqiStP",
      "DDHC-MORD-01": "https://drive.google.com/open?id=1D6rs09XBmzlRCfcH-zo5WILzY5Gb7a4R",
      "DDHC-MORD-02": "https://drive.google.com/open?id=1t3U87g9JHNX3LTnfJbjVIhN6k2hTu6pO",
      "DDHC-MORD-03": "https://drive.google.com/open?id=1hRguV78PccOIQbq5c4HRbH1dHRHFeCHY",
      "DDHC-MORD-04": "https://drive.google.com/open?id=1SGQnrXMdFgGgJOVSmW6qTdp8DD1MMYFG",
      "DDHC-MORD-05": "https://drive.google.com/open?id=1oFfxepMsdj99o9dJN59T6CW3MoTSaFM_",
      "DDHC-OotA": "https://drive.google.com/open?id=0B9NR7rHEJNUGbmNYMlJxcVhidjg",
      "DDHC-PotA": "https://drive.google.com/open?id=0B9NR7rHEJNUGUGdXRlozR0hNZE0",
      "DDHC-RoT": "https://drive.google.com/open?id=0B9NR7rHEJNUGdmRLYXlZdi00cXc",
      "DDHC-SKT": "https://drive.google.com/open?id=0B9NR7rHEJNUGcWZScUhLU1UzSDA",
      "DDHC-ToA": "https://drive.google.com/open?id=0B9E-VnDwJVBSLTB6NmFFbjBFSUU",
      "DDHC-TOA-10": "https://drive.google.com/open?id=0B9NR7rHEJNUGN2tsczcwVEkyMFk",
      "DDHC-TOA-11": "https://drive.google.com/open?id=0B9NR7rHEJNUGb0NtcjhSaWJpc28",
      "DDHC-TOA-12": "https://drive.google.com/open?id=0B9NR7rHEJNUGWnBLc3JVbE5iakE",
      "DDHC-TOA-13": "https://drive.google.com/open?id=1ohoUpjxznheIgjUbjtwyQ5dP8vRn8t-s",
      "DDHC-TOA-14": "https://drive.google.com/open?id=1OkbP0VpZqJlDbTodyv2-l0WjK5wvZHab",
      "DDHC-TOA-15": "https://drive.google.com/open?id=17xLmH2ItFryzw7m8BXvi_e3xdGHxP-7e",
      "DDHC-TOA-2": "https://drive.google.com/open?id=1vQQyh4JZGbUYm_AsSWh6nYFl_UUBIu3u",
      "DDHC-TOA-3": "https://drive.google.com/open?id=0B9NR7rHEJNUGekk0cnJfb2RiZk0",
      "DDHC-TOA-4": "https://drive.google.com/open?id=0B9NR7rHEJNUGczVQbl95aExZWTg",
      "DDHC-TOA-5": "https://drive.google.com/open?id=0B9NR7rHEJNUGSk5URmFwYmxkdEk",
      "DDHC-TOA-6": "https://drive.google.com/open?id=0B9NR7rHEJNUGaE9ncFBBSUliV1E",
      "DDHC-TOA-7": "https://drive.google.com/open?id=0B9NR7rHEJNUGUE5UMUdIejEwNjA",
      "DDHC-TOA-8": "https://drive.google.com/open?id=0B9NR7rHEJNUGeEFyWFBXRDBka00",
      "DDHC-TOA-9": "https://drive.google.com/open?id=0B9NR7rHEJNUGXzlJQmVNUEN6NE0",
      "DDHC-TYP": "https://drive.google.com/open?id=0B9NR7rHEJNUGM1RtTDFHeXFwMG8",
      "DDHC-TYP-A": "https://drive.google.com/open?id=0B9NR7rHEJNUGQ1JfUXNfTHJzZUU",
      "DDHC-TYP-C": "https://drive.google.com/open?id=0B9NR7rHEJNUGbm9iYnh2UnBsbDA",
      "DDHC-TYP-G": "https://drive.google.com/open?id=0B9NR7rHEJNUGWDNNMHBkd2xTTUk",
      "DDHC-WDH-01": "https://drive.google.com/open?id=1v9G8T4bGIwHrQKsOtd4oIcMkp_SWs1Pu",
      "DDHC-WDH-02": "https://drive.google.com/open?id=1vC-EQakkNcgyQiP3eH_4Ei6VnaJKrpQT",
      "DDHC-WDH-03": "https://drive.google.com/open?id=132SygGQRkZoWFbuwMr_d9G7OoSCkYWiU",
      "DDHC-WDH-04": "https://drive.google.com/open?id=1hkjwgu4W8Jcj5SESY56T6lDmYkuvccnH",
      "DDHC-XGE-01": "https://drive.google.com/open?id=1SCG0EhFDz9XcXRRE9TRxvCNbG2ItkhDl",
      "DDIA-04": "https://drive.google.com/open?id=0B9NR7rHEJNUGakw3dG1BZmdITVE",
      "DDIA-05": "https://drive.google.com/open?id=0B9NR7rHEJNUGSUZIemR4WDZfSkE",
      "DDIA-MORD": "https://drive.google.com/open?id=1ucRhB5yJ-I_2h8ovAlzaKxMXDLDj7asL",
      "DDIA-VOLO": "https://drive.google.com/open?id=0B9NR7rHEJNUGamhZZjRnMXYydU0",
      "DDIA-XGE": "https://drive.google.com/open?id=0B9NR7rHEJNUGeXczWHo5V0xkM28",
      "DDIA06-SUNLESSCITADEL": "https://drive.google.com/open?id=0B9NR7rHEJNUGQ1JfUXNfTHJzZUU",
      "RMH-01": "https://drive.google.com/file/d/1uFRD4FxF7hazGdK6Ld4pavg75z8wXj9d/view?usp=sharing",
      "RMH-02": "https://drive.google.com/file/d/1O-k2IiBajZMy5ffe_TsOGcmMt71HguQp/view?usp=sharing",
      "RMH-03": "https://drive.google.com/file/d/1drDL98aRgIDMv53iiznxOrc3A6pMy8mq/view?usp=sharing",
      "RMH-04": "https://drive.google.com/file/d/15W4ho-1MdMktaTT7rm7x4hQAvToG7RNt/view?usp=sharing",
      "RMH-05": "https://drive.google.com/file/d/1WurwUxtkfm9F637oqwt7hKlAAYQuSB20/view?usp=sharing",
      "RMH-06": "https://drive.google.com/file/d/1FR3ZnS6H-hlWFTTj7tLT0g0lB5Qn0IhO/view?usp=sharing",
      "RMH-07": "https://drive.google.com/file/d/1llhpahnTWtpe2BJnNkFNdzMg7TiqvQHU/view?usp=sharing",
      "RMH-08": "https://drive.google.com/file/d/1gTP9obkgXKqiAmgNseiVK2i0PUeguDDQ/view?usp=sharing",
      "RMH-09": "https://drive.google.com/file/d/1fU7hT1229nqjJp4q0h0teKhlIc3KUp17/view?usp=sharing",
      "RMH-10": "https://drive.google.com/file/d/1r9m5vNbPVixfpcKozZFUr36u3E6_4_dE/view?usp=sharing",
      "RMH-11": "https://drive.google.com/file/d/1apPHPTfHOUXEOZ4O9cpShJ1_P7hGCbm1/view?usp=sharing",
      "RMH-12": "https://drive.google.com/file/d/1rrS0KSRj168RqNsSMO7rZi1QEMohvs1Y/view?usp=sharing",
      "RMH-EP-01": "https://drive.google.com/file/d/1sPtwvQL1UDVERc8vhAIR-CjuejXByccD/view?usp=sharing",
      "RMH-EP-02": "https://drive.google.com/file/d/1EOkAr-rGyHoFm_-BC3gausYNktePL-CY/view?usp=sharing",
      "DC-POA-PND-1": "https://drive.google.com/open?id=1ajw3pEacs6mkxIGL-MV450Zq8qb0bZzT&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "DC-POA-PND-2": "https://drive.google.com/open?id=1XaHjenH8FlFlpA8nT-WrZlzMb-5JzV7d&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "DC-POA-PND-3": "http://DC-POA-PND-3 The Watcher in the Attic v0.9.1",
      "DC-POA-PND-4": "https://drive.google.com/open?id=1KgN0aGDzRg4HnFAziB9SxvgHNEZHonQg&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "DC-POA-PND-5": "https://drive.google.com/open?id=1m7c284d5Z2ZFk5-VKmDom7bZEbhq-fXM&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "WBW-DC-CONMAR-01": "https://drive.google.com/open?id=1u94bUnVmxZ21yBSHRE2IPZLs_oYRihnS&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "WBW-DC-DCAF01": "https://drive.google.com/open?id=1VkL85gRrl7_v-hfeYy_kDCviwib9lJ5q&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "WBW-DC-DCAF01B": "https://drive.google.com/open?id=1-BqozrhFR-pEc_mi6GUx66wa6KpY2gCS&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "WBW-DC-DCAF02": "https://drive.google.com/open?id=17mQv0KqjloHBxmDXnA-7-DHH_V1IrIeG&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "WBW-DC-FDC-01": "https://drive.google.com/open?id=1_uX6sLJjAk--WKpTVgDAk8eJReDRT_LO&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "WBW-DC-FDC-03": "https://drive.google.com/open?id=1VFaoKx-tRwT3I3nFu62Dr-K4fklmfDbN&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "WBW-DC-FDC-05": "https://drive.google.com/open?id=1oM4ujLzR2XRnLfU6BWbWrZd78wXWcw5s&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "WBW-DC-FDC-07": "https://drive.google.com/open?id=1fRiQ_2SdleJ4dD_lfnISjNE5L71KAx4R&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "WBW-DC-FDC-08": "https://drive.google.com/open?id=133dCxKx_fFfmkE2Xft3Tb1_TAFui60nn&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "WBW-DC-FDC-09": "https://drive.google.com/open?id=1mxQjUu4cchuhoX9BwlVfaH77kLJDkHHw&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "WBW-DC-NJ-COU-01": "https://drive.google.com/open?id=1ukFsbQhC4xfP1XlyANiNMugD0HkQN98B&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "WBW-DC-TRI-01": "https://drive.google.com/open?id=1k30P0_vRgTOz1GOQTvk0V0X6nFcfF1eT&authuser=groupodeeandee%40gmail.com&usp=drive_fs",
      "WBW-DC-TRI-02": "https://drive.google.com/open?id=1dFSHnmkjvfrdW3LKR0jwXaJ1GdqfMFPv&authuser=groupodeeandee%40gmail.com&usp=drive_fs"
    }

    # 3. Migrate
    new_inventory = {}
    failed_matches = {}
    success_count = 0
    fail_count = 0

    print("Migrating inventory...")
    for code, url in original_inventory.items():
        lookup_code = code.strip().upper()
        
        product_id = None
        # a) Manual override
        if code in overrides:
            product_id = overrides[code]
        # b) Direct match
        elif lookup_code in code_to_id:
            product_id = code_to_id[lookup_code]
        # c) EB specific normalization: DDAL-EB-01 -> EB-01
        elif lookup_code.startswith('DDAL-EB-'):
            short_code = lookup_code.replace('DDAL-', '')
            if short_code in code_to_id:
                product_id = code_to_id[short_code]
        # d) Other prefix normalization
        elif lookup_code.startswith('DDAL-'):
            short_code = lookup_code.replace('DDAL-', '')
            if short_code in code_to_id:
                product_id = code_to_id[short_code]
        
        if product_id:
            new_inventory[product_id] = url
            success_count += 1
        else:
            failed_matches[code] = url
            fail_count += 1

    # 4. Save results
    with open(private_inventory_path, 'w', encoding='utf-8') as f:
        json.dump(new_inventory, f, indent=2)

    if failed_matches:
        with open(failed_path, 'w', encoding='utf-8') as f:
            json.dump(failed_matches, f, indent=2)
        print(f"Saved {fail_count} failed matches to {failed_path}")
    else:
        if failed_path.exists():
            os.remove(failed_path)

    print(f"Migration complete: {success_count} successful, {fail_count} failed.")

    # 5. Refactoring Plan
    if not refactor_doc_path.exists():
        refactor_content = """# Refactoring Plan

## Local Storage Migration
- **Goal**: Move from external JSON/cookie-based inventory to browser Local Storage.
- **Benefits**: Better persistence, no size limits like cookies, easier offline access.
- **Tasks**:
    - Update `filter.js` to load from/save to `localStorage`.
    - Provide import/export functionality for the `product_id -> URL` mapping.
    - Deprecate cookie-based `inventory_url` in favor of local management.
"""
        with open(refactor_doc_path, 'w', encoding='utf-8') as f:
            f.write(refactor_content)
    else:
        with open(refactor_doc_path, 'r', encoding='utf-8') as f:
            content = f.read()
        if "Local Storage for Private Inventory" not in content:
            with open(refactor_doc_path, 'a', encoding='utf-8') as f:
                f.write("\n## Local Storage for Private Inventory (Added 2026-02-09)\n- Maintain the list of product ID -> drive link in local storage as an alternative plan.\n")

if __name__ == "__main__":
    migrate_inventory()
